create table agent_analysis_context (
    id bigint generated by default as identity primary key,
    agent_run_id bigint not null,
    schema_version varchar(40) not null,
    head_sha varchar(80) not null,
    base_sha varchar(80),
    archive_ref varchar(500),
    repository_profile_json text,
    changed_diff text,
    change_set_json text,
    retrieved_context_json text,
    findings_json text,
    gate_json text,
    stage varchar(40) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uq_agent_analysis_context_run unique (agent_run_id),
    constraint fk_agent_analysis_context_run foreign key (agent_run_id) references agent_run(id)
);

create index idx_agent_analysis_context_head on agent_analysis_context(head_sha);
