create table agent_scm_context (
    id bigint generated by default as identity primary key,
    agent_run_id bigint not null,
    provider varchar(32) not null,
    installation_id bigint not null,
    repository_full_name varchar(255) not null,
    repository_clone_url varchar(512) not null,
    pull_request_number integer not null,
    base_sha varchar(80) not null,
    head_sha varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uq_agent_scm_context_run unique (agent_run_id),
    constraint fk_agent_scm_context_run foreign key (agent_run_id) references agent_run(id),
    constraint fk_agent_scm_context_installation foreign key (installation_id) references scm_installation(id)
);

create table agent_publication (
    id bigint generated by default as identity primary key,
    agent_run_id bigint not null,
    idempotency_key varchar(200) not null,
    status varchar(32) not null,
    response_codes varchar(255),
    message varchar(2000),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uq_agent_publication_key unique (idempotency_key),
    constraint fk_agent_publication_run foreign key (agent_run_id) references agent_run(id)
);

create index idx_agent_publication_run on agent_publication(agent_run_id);
