spring:
  datasource:
    url: jdbc:h2:mem:code_review;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  rabbitmq:
    dynamic: false
    listener:
      simple:
        auto-startup: false

management:
  health:
    rabbit:
      enabled: false

logging:
  level:
    com.example.codereview: info

app:
  git:
    allow-local-path: true
